services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    container_name: triton-inference-server
    restart: unless-stopped
    command: tritonserver --model-repository=/models --strict-model-config=false
    runtime: nvidia
    shm_size: 1gb
    ports:
      - "8000:8000"   # HTTP
      - "8001:8001"   # gRPC
      - "8002:8002"   # Prometheus metrics
    volumes:
      - ./models:/models
    networks:
      - envisions
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
  triton-model-builder:
    image: nvcr.io/nvidia/tritonserver:24.08-py3
    container_name: triton-model-builder
    profiles: ["build"]
    runtime: nvidia
    entrypoint: ["/bin/bash", "/tools/build_engine.sh"]
    volumes:
      - ./models:/models
      - ./tools:/tools:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
  services-python-1:
    image: python-counting-services-python-1:latest
    container_name: services-python-b1
    restart: unless-stopped
    env_file:
      - .env_b1
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - envisions
    depends_on:
      - triton
    volumes:
      - /home/irengi/Documents/Python/epiwalk/v3-dashboard/python-counting:/app
    environment:
      - TRITON_URL=triton:8001
  services-python-t1:
    image: python-counting-services-python-1:latest
    container_name: services-python-t1
    restart: unless-stopped
    env_file:
      - .env_T1
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - envisions
    depends_on:
      - triton
    volumes:
      - /home/irengi/Documents/Python/epiwalk/v3-dashboard/python-counting:/app
    environment:
      - TRITON_URL=triton:8001
networks:
  envisions:
    driver: bridge
